# Generated by Django 3.2.9 on 2021-11-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
