# Generated by Django 3.2.9 on 2021-11-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dessert_drink_pasta_salad_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='side',
            name='ingredients',
        ),
    ]
